const countryData = [
	{ language: "english", code: "gb" },
	{ language: "austrian", code: "at" },
	{ language: "belgian", code: "be" },
	{ language: "普通话", code: "cn" },
	{ language: "croatian", code: "hr" },
	{ language: "czech", code: "cz" },
	{ language: "dansk", code: "dk" },
	{ language: "nederlands", code: "nl" },
	{ language: "estonian", code: "ee" },
	{ language: "finnish", code: "fi" },
	{ language: "français", code: "fr" },
	{ language: "deutsch", code: "de" },
	{ language: "ελληνικά", code: "gr" },
	{ language: "hungarian", code: "hu" },
	{ language: "हिन्दी", code: "in" },
	{ language: "iranian", code: "ir" },
	{ language: "iraqi", code: "iq" },
	{ language: "italiano", code: "it" },
	{ language: "日本語", code: "jp" },
	{ language: "kazakhstani", code: "kz" },
	{ language: "latvian", code: "lv" },
	{ language: "lithuanian", code: "lt" },
	{ language: "norsk", code: "no" },
	{ language: "pakistani", code: "pk" },
	{ language: "polski", code: "pl" },
	{ language: "português", code: "pt" },
	{ language: "romanian", code: "ro" },
	{ language: "serbian", code: "cs" },
	{ language: "slovakian", code: "sk" },
	{ language: "slovenian", code: "si" },
	{ language: "한국어/조선말", code: "kr" },
	{ language: "español", code: "es" },
	{ language: "svenska", code: "se" },
	{ language: "swiss", code: "ch" },
	{ language: "thai", code: "th" },
	{ language: "türkçe", code: "tr" },
	{ language: "український", code: "ua" },
];

export default countryData;
